# Generated by Django 4.0.2 on 2022-06-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Registroo',
        ),
    ]
