# Generated by Django 4.0.2 on 2022-06-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_delete_contacto_delete_registroo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('Nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('Rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('Apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('Email', models.CharField(max_length=20, verbose_name='E-mail')),
                ('Asunto', models.CharField(max_length=9, verbose_name='Asunto')),
                ('Asunto2', models.CharField(max_length=20, verbose_name='Asunto2')),
            ],
        ),
        migrations.CreateModel(
            name='Registroo',
            fields=[
                ('Nombre', models.CharField(max_length=6, verbose_name='Nombre')),
                ('Rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('Edad', models.CharField(max_length=2, verbose_name='Edad')),
                ('Email', models.CharField(max_length=20, verbose_name='E-mail')),
                ('Telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('Contraseña', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
    ]
