# Generated by Django 4.0.4 on 2022-06-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprar',
            fields=[
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Talla', models.CharField(max_length=1, verbose_name='Talla')),
                ('Monto', models.CharField(max_length=9, verbose_name='Monto')),
                ('Pago', models.CharField(max_length=100, verbose_name='Pago')),
                ('Tarjeta', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Tarjeta')),
                ('Fecha_expira', models.CharField(max_length=100, verbose_name='Fecha de expiracion')),
                ('Cvv', models.CharField(max_length=100, verbose_name='CVV')),
                ('Comentario', models.CharField(max_length=100, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Stock', models.CharField(max_length=20, verbose_name='Stock')),
            ],
        ),
    ]
