# Generated by Django 4.0.4 on 2022-06-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprar',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Registroo',
        ),
    ]
